# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_db.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vector_db.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvector_db.proto\x12\x0e\x63orevector.api\"<\n\rInsertRequest\x12+\n\x07vectors\x18\x01 \x03(\x0b\x32\x1a.corevector.api.VectorData\"\x1c\n\nVectorData\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\'\n\x0eInsertResponse\x12\x15\n\rtotal_vectors\x18\x01 \x01(\x03\")\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\"?\n\x0eSearchResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.corevector.api.SearchResult\",\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"\x1f\n\x0bSaveRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"0\n\x0cSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0bLoadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"G\n\x0cLoadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rtotal_vectors\x18\x03 \x01(\x03\x32\xa2\x02\n\x08VectorDB\x12G\n\x06Insert\x12\x1d.corevector.api.InsertRequest\x1a\x1e.corevector.api.InsertResponse\x12G\n\x06Search\x12\x1d.corevector.api.SearchRequest\x1a\x1e.corevector.api.SearchResponse\x12\x41\n\x04Save\x12\x1b.corevector.api.SaveRequest\x1a\x1c.corevector.api.SaveResponse\x12\x41\n\x04Load\x12\x1b.corevector.api.LoadRequest\x1a\x1c.corevector.api.LoadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_db_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST']._serialized_start=35
  _globals['_INSERTREQUEST']._serialized_end=95
  _globals['_VECTORDATA']._serialized_start=97
  _globals['_VECTORDATA']._serialized_end=125
  _globals['_INSERTRESPONSE']._serialized_start=127
  _globals['_INSERTRESPONSE']._serialized_end=166
  _globals['_SEARCHREQUEST']._serialized_start=168
  _globals['_SEARCHREQUEST']._serialized_end=209
  _globals['_SEARCHRESPONSE']._serialized_start=211
  _globals['_SEARCHRESPONSE']._serialized_end=274
  _globals['_SEARCHRESULT']._serialized_start=276
  _globals['_SEARCHRESULT']._serialized_end=320
  _globals['_SAVEREQUEST']._serialized_start=322
  _globals['_SAVEREQUEST']._serialized_end=353
  _globals['_SAVERESPONSE']._serialized_start=355
  _globals['_SAVERESPONSE']._serialized_end=403
  _globals['_LOADREQUEST']._serialized_start=405
  _globals['_LOADREQUEST']._serialized_end=436
  _globals['_LOADRESPONSE']._serialized_start=438
  _globals['_LOADRESPONSE']._serialized_end=509
  _globals['_VECTORDB']._serialized_start=512
  _globals['_VECTORDB']._serialized_end=802
# @@protoc_insertion_point(module_scope)
