# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vector_db_pb2 as vector__db__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vector_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDBStub(object):
    """The VectorDB service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/corevector.api.VectorDB/Insert',
                request_serializer=vector__db__pb2.InsertRequest.SerializeToString,
                response_deserializer=vector__db__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/corevector.api.VectorDB/Search',
                request_serializer=vector__db__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__db__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Save = channel.unary_unary(
                '/corevector.api.VectorDB/Save',
                request_serializer=vector__db__pb2.SaveRequest.SerializeToString,
                response_deserializer=vector__db__pb2.SaveResponse.FromString,
                _registered_method=True)
        self.Load = channel.unary_unary(
                '/corevector.api.VectorDB/Load',
                request_serializer=vector__db__pb2.LoadRequest.SerializeToString,
                response_deserializer=vector__db__pb2.LoadResponse.FromString,
                _registered_method=True)


class VectorDBServicer(object):
    """The VectorDB service definition
    """

    def Insert(self, request, context):
        """Insert one or more vectors into the index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search for the k nearest neighbors of a query vector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Save the index to a binary file on disk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Load(self, request, context):
        """Load the index from a binary file on disk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=vector__db__pb2.InsertRequest.FromString,
                    response_serializer=vector__db__pb2.InsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vector__db__pb2.SearchRequest.FromString,
                    response_serializer=vector__db__pb2.SearchResponse.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=vector__db__pb2.SaveRequest.FromString,
                    response_serializer=vector__db__pb2.SaveResponse.SerializeToString,
            ),
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=vector__db__pb2.LoadRequest.FromString,
                    response_serializer=vector__db__pb2.LoadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'corevector.api.VectorDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('corevector.api.VectorDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDB(object):
    """The VectorDB service definition
    """

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/corevector.api.VectorDB/Insert',
            vector__db__pb2.InsertRequest.SerializeToString,
            vector__db__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/corevector.api.VectorDB/Search',
            vector__db__pb2.SearchRequest.SerializeToString,
            vector__db__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/corevector.api.VectorDB/Save',
            vector__db__pb2.SaveRequest.SerializeToString,
            vector__db__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/corevector.api.VectorDB/Load',
            vector__db__pb2.LoadRequest.SerializeToString,
            vector__db__pb2.LoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
